### ISSUE TITLE
add wake island

### ISSUE THREAD

**Issue by oldLucke** [gruppe-adler/maps.gruppe-adler.de#1]
https://github.com/oldLucke/arma-map-tiles-wake

**Comment by DerZade** [comment]
Hey @oldLucke würdest du die repo zu [der Orga](https://github.com/arma-map-tiles) (hast auch ne Invite bekommen) rüber schieben. Dann ist alles an einem Platz und so. 
Könntest du dann auch noch einen PR erstellen? Wenn du Hilfe dabei brauchst frag einfach :D

**Comment by oldLucke** [comment]
Hallo @DerZade. Ich habe vergessen [die Repositorie](https://github.com/arma-map-tiles/arma-map-tiles-wake) umzubenennen und denke mal ihr wollte das einheitlich haben. Ich mach dann den PR.

**Comment by TheWillard** [comment]
done

**Comment by oldLucke** [comment]
fixed in #2
